PPW_Story_7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_7.urls'))
]

story_7/urls.py
from django.urls import path
from . import views

app_name = 'story_7'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirmation/', views.confirm, name='confirmation')
]   

story_7/models.py
from django.db import models
import datetime

# Create your models here.

class Status(models.Model):
    name = models.CharField(max_length = 255)
    message = models.CharField(max_length = 255)
    post_date = models.DateTimeField(auto_now_add=True)

story_7/forms.py
from django import forms

class StatusInputForm(forms.Form):
    name = forms.CharField(max_length= None, label = 'Name', initial='', widget = forms.TextInput({'id':'name'}))
    status_message = forms.CharField(label = 'Status', initial='', widget = forms.TextInput({'id':'status'}))
    

story_7/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

# Create your views here.

def index(request):
    statuses = Status.objects.all()
    status_form = StatusInputForm()
    if request.method == 'GET':
        return render(request, 'index.html', {'statuses' : statuses, 'status_form': status_form})

    if request.method == 'POST':
        status_input = StatusInputForm(request.POST)
        if status_input.is_valid():
            status = Status(name = status_input.data['name'], message = status_input.data['status_message'])
            status.save()
            return render(request, 'index.html', {'statuses' : statuses, 'status_form': status_form})
        else:
            return render(request, 'index.html', {'statuses' : statuses, 'status_form': status_form})

    

def confirm(request):
    if request.method == 'POST':
        status_input = StatusInputForm(request.POST)
        if status_input.is_valid():
            confirm_name = status_input.data['name']
            confirm_status = status_input.data['status_message']
            confirm_form = StatusInputForm(initial={'name':confirm_name, 'status_message':confirm_status})
            return render(request, 'confirm.html', {'confirm_form' : confirm_form})
        else:
            response = redirect('/')
            return response
    if request.method == 'GET':
        return redirect('/')


    

story_7/templates/confirm.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Confirm</title>
    </head>
    <body>
        <form action="{% url 'story_7:index' %}" method="POST">
            {% csrf_token %}
            {{confirm_form}}
            <p>Are you sure you want to post this status</p>
            <input type="Submit" value="YES" id="yes">
            <input type="submit" value="NO" id="no" formaction="{% url 'story_7:index' %}">
        </form>
    </body>
</html>

story_7/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Home</title>
    </head>
    <body>
        <form method="POST" action="{% url 'story_7:confirmation' %}">
            {% csrf_token %}
            {{status_form}}
            <input type="Submit" value="post status" id="submit">
        </form>

        <div>
            <ul>
                {% for status in statuses %}
                <li>
                    <h3>
                        {{ status.name }}
                    </h3>
                    <p>
                        {{ status.message }}
                    </p>
                </li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>